https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
# https://news.ycombinator.com/rss
# http://rss.cnn.com/rss/cnn_topstories.rss
# https://www.latimes.com/california/rss2.0.xml
# https://www.chicagotribune.com/arcio/rss/category/news/breaking/
# https://timesofindia.indiatimes.com/rssfeedstopstories.cms
# https://www.aljazeera.com/xml/rss/all.xml
# https://feeds.bbci.co.uk/news/video_and_audio/news_front_page/rss.xml
# http://feeds.foxnews.com/foxnews/latest
# https://feeds.washingtonpost.com/rss/local
# http://feeds.marketwatch.com/marketwatch/topstories/
# https://www.theguardian.com/world/rss
# https://www.democracynow.org/democracynow.rss
# https://feeds.thedailybeast.com/rss/articles
# https://www.buzzfeed.com/world.xml
# https://defence-blog.com/feed/
# https://www.thecipherbrief.com/feed/
# https://www.rt.com/rss/news/
# https://feeds.npr.org/1004/rss.xml
# https://www.cbc.ca/cmlink/rss-world
# http://www.independent.co.uk/news/world/rss
# https://www.euronews.com/rss?level=theme&name=news
# https://www.smh.com.au/rss/world.xml
# https://www.france24.com/en/rss
# https://feeds.skynews.com/feeds/rss/world.xml
# https://www.scmp.com/rss/91/feed
# https://www.channelnewsasia.com/api/v1/rss-outbound-feed
# https://www1.cbn.com/app_feeds/rss/news/rss.php?section=world
# https://www.dkoding.in/feed/
# https://feeds.theworld.org/stories/feed/everything
# https://wan-ifra.org/news/feed/
# https://warontherocks.com/feed/
# https://feeds.thelocal.com/rss/es
# https://kwttoday.com/feed/
# https://radarr.africa/feed/
# https://ifpnews.com/feed
# https://newsblaze.com/feed/
# https://www.neweurope.eu/category/world/feed/
# https://rightwirereport.com/feed/
# https://www.watchdoguganda.com/feed
# https://warritatafo.com/feed/
# https://globalpressjournal.com/feed/
# https://foreignpolicy.com/feed/
# https://foreignpolicyblogs.com/feed/
# http://www.fpri.org/feed/
# https://foreignpolicyi.org/feed/
# https://foreignpolicyrising.com/feed/
# https://medium.com/feed/tag/foreign-policy
# https://www.diplomatie.gouv.fr/spip.php?page=backend&id_rubrique=53404/feed
# https://mid.ru/rss
# https://www.thenation.com/subject/foreign-policy/feed/
# https://www.politico.eu/tag/foreign-policy/feed/
# https://www.allsides.com/taxonomy/term/303/feed
# https://carnegieendowment.org/rss/solr/?fa=feeds&lang=en
# https://blogs.fcdo.gov.uk/feed/
# https://thehill.com/taxonomy/term/1138/feed
# https://www.seattletimes.com/seattle-news/feed/